name: Test
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'test/**'
      - 'shared/**'
      - '.github/workflows/**'
env:
  SOLUTION: Rougamo.sln
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x
          
      - name: Restore NuGets
        run: dotnet restore ${{ env.SOLUTION }}
        
      - name: Build Solution in DEBUG
        run: dotnet build --configuration Debug --no-restore ${{ env.SOLUTION }}
        
      - name: Test in DEBUG
        run: dotnet test --configuration Debug --no-build ${{ env.SOLUTION }}
        
      - name: Build Solution in RELEASE
        run: dotnet build --configuration Release --no-restore ${{ env.SOLUTION }}
        
      - name: Test in RELEASE
        run: dotnet test --configuration Release --no-build ${{ env.SOLUTION }}
        
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x

      - name: Install OpenSSL 1.1
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu4.4_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu4.4_amd64.deb
          
      - name: Restore NuGets
        run: dotnet restore ${{ env.SOLUTION }}
        
      - name: Build Solution in DEBUG
        run: dotnet build --configuration Debug --no-restore ${{ env.SOLUTION }}
        
      - name: Test in DEBUG with netcoreapp3.1
        run: dotnet test --configuration Debug --no-build --framework netcoreapp3.1 test/Rougamo.Fody.Tests/Rougamo.Fody.Tests.csproj
        
      - name: Test in DEBUG with net6.0
        run: dotnet test --configuration Debug --no-build --framework net6.0 test/Rougamo.Fody.Tests/Rougamo.Fody.Tests.csproj
        
      - name: Test in DEBUG with net8.0
        run: dotnet test --configuration Debug --no-build --framework net8.0 test/Rougamo.Fody.Tests/Rougamo.Fody.Tests.csproj
        
      - name: Test in DEBUG with net9.0
        run: dotnet test --configuration Debug --no-build --framework net9.0 test/Rougamo.Fody.Tests/Rougamo.Fody.Tests.csproj
        
      - name: Test Analyzers in DEBUG with net8.0
        run: dotnet test --configuration Debug --no-build --framework net8.0 test/Rougamo.Analyzers.Tests/Rougamo.Analyzers.Tests.csproj
        
      - name: Build Solution in RELEASE
        run: dotnet build --configuration Release --no-restore ${{ env.SOLUTION }}
        
      - name: Test in RELEASE with netcoreapp3.1
        run: dotnet test --configuration Release --no-build --framework netcoreapp3.1 test/Rougamo.Fody.Tests/Rougamo.Fody.Tests.csproj
        
      - name: Test in RELEASE with net6.0
        run: dotnet test --configuration Release --no-build --framework net6.0 test/Rougamo.Fody.Tests/Rougamo.Fody.Tests.csproj
        
      - name: Test in RELEASE with net8.0
        run: dotnet test --configuration Release --no-build --framework net8.0 test/Rougamo.Fody.Tests/Rougamo.Fody.Tests.csproj
        
      - name: Test in RELEASE with net9.0
        run: dotnet test --configuration Release --no-build --framework net9.0 test/Rougamo.Fody.Tests/Rougamo.Fody.Tests.csproj
        
      - name: Test in RELEASE with net8.0
        run: dotnet test --configuration Release --no-build --framework net8.0 test/Rougamo.Analyzers.Tests/Rougamo.Analyzers.Tests.csproj
